default_stages: [commit]
default_language_version:
  python: python3.9
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest test/test.py -v
        language: python
        pass_filenames: false
        always_run: true